language: python
python:
- "3.6"
- "pypy3.5"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6
    - gcc-4.8

# command to install dependencies
before_install:
- chmod 777 ./.travis/install-protoc.sh
- ./.travis/install-protoc.sh 2.6.1

install:
- pip install -r requirements.txt
- pip install -r requirements-test.txt
# command to run tests
script:
- python init.py
- pytest --cov=./ --ignore=protobuf-2.6.1/

after_success:
- codecov
